version: "3.7"
services:
  # # Nginx Reverse Proxy - Exposed HTTP(S) Interface
  proxy:
    build:
      context: proxy
    restart: always
    depends_on:
      - server
    networks: 
     - felnet
    ports:
      - $PROXY_HTTP_PORT:80
      - $PROXY_SSL_PORT:443

  # Database - Main Site Database
  db:
    build:
      context: db
    restart: always
    networks:
      - felnet
    volumes:
      - $DB_DATA_DIR:/var/lib/postgresql/data
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_ROOT_USER
      POSTGRES_PASSWORD: $POSTGRES_ROOT_PASSWORD
      POSTGRES_DB: $POSTGRES_DB_NAME

  # pgAdmin4 Instance - Administration Interface to Database
  admin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - db
    networks:
      - felnet
    ports:
      - $ADMIN_PORT:80
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD

  # Express Server - Main Site Server
  server:
    build:
      context: server
    restart: always
    depends_on:
      - db
    networks:
      - felnet
    ports:
      - $SERVER_PORT:3000
    environment:
      DB_USER: $SERVER_POSTGRES_USER
      DB_PASSWORD: $SERVER_POSTGRES_PASSWORD
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: $POSTGRES_DB_NAME
      JWT_SECRET: $SERVER_SECRET_KEY


networks:
  felnet:
    driver: bridge
